### PR TITLE
deps(*) move from github.com/pkg/errors to 'errors' and 'fmt'

### PR DESCRIPTION
**Pull request by mmorel-35**
### Summary

The package https://github.com/pkg/errors is not maintained anymore.
This PR replaces https://github.com/pkg/errors with official errors and fmt golang packages

### Testing

- [ ] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes

### Backwards compatibility

- [ ] Update [`UPGRADE.md`](/UPGRADE.md) with any steps users will need to take when upgrading.
- [ ] Add `backport-to-stable` label if the code follows our [backporting policy](/CONTRIBUTING.md#backporting)

Signed-off-by: Matthieu MOREL <mmorel-35@users.noreply.github.com>

### CODE REVIEW

**Review by michaelbeaumont — CHANGES_REQUESTED** [review]
I have the same reservations outlined [here](https://github.com/thanos-io/thanos/issues/5176)

**Comment by lahabana** [comment]
OK so should we just keep it as is until there's potentially a better API in the lib? @jakubdyszkiewicz what's your opinion here?

**Comment by slonka** [comment]
Is there a risk of a security vuln not getting patched if we stay on this?

**Comment by lahabana** [comment]
We've decided that this change wasn't worth it for the moment. Thanks!

**Pull request closed without merging**
