### PR TITLE
feat(service-insights): add external service in api

### LINKED ISSUE #5077: Enrich service-insights endpoint to include external services
### Description

(Related to https://github.com/kumahq/kuma-gui/issues/383)

- Add external services to the items returned by this endpoint. An external service insight on this endpoint has the fields `type`, `mesh`, `name`, `creationTime`, `modificationTime`, `serviceType: 'external'`, and `address`.
- Add a `serviceType` field of type string with the possible values `'internal'` and `'external'`.
- For service insights, add the field `address` and set it to the .mesh address. This should also be added to the service insights endpoint that retrieve the actual entity.

### PR DESCRIPTION
**Pull request by lahabana**
- also make vip port configurable
- rewrite some tests to get rid of unecessary shared state and locks

Fix #5077

Signed-off-by: Charly Molter <charly.molter@konghq.com>

### Checklist prior to review

- [] Link to docs PR or issue --
- [x] Link to UI issue or PR --
- [x] Is the [issue worked on linked][1]? --
- [x] The PR does not hardcode values that might break projects that depend on kuma (e.g. "kumahq" as a image registry) --
- [x] The PR will work for both Linux and Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Unit Tests --
- [x] E2E Tests --
- [x] Manual Universal Tests --
- [x] Manual Kubernetes Tests --
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [x] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by lahabana** [comment]
@kleinfreund this is what you need for the service view I believe

**Comment by lahabana** [comment]
Anyone feel free to take over this PR to unblock Philipp

**Comment by jakubdyszkiewicz** [comment]
I'm taking over this PR

**Comment by kleinfreund** [comment]
@jakubdyszkiewicz @lahabana Thanks for picking this up. I’ll have a look at this soon. 👍

**Pull request merged**
