### PR TITLE
feat(kumactl): add initial Gateway CRD installation

### PR DESCRIPTION
**Pull request by jpeach**
### Summary

Add an initial kumactl subcommand to install the Gateway API CRDs. The idea is that this would eventually be extended to generate YAML to install the controller itself, the validating webhook and any any
other necessary components.

### Full changelog

N/A

### Issues resolved

Updates #3317

### Documentation

N/A

### Testing

- [ ] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [x] Manual testing on Kubernetes 

### Backwards compatibility

- [ ] ~~Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.~~

### CODE REVIEW

**Comment by jpeach** [comment]
WDYT @michaelbeaumont ?

**Comment by jpeach** [comment]
> WDYT @michaelbeaumont ?

I moved this around a bit and it slots into `install crds` and `install control-plane` with minimal changes. I think the main question is whether this is the UX that we want for this.

- should we make this conditional on the gateway build flags?
- or should we have a CLI flag to toggle it (instead of, or in addition to the build flag)?
- installing the Gateway APIs in `install crds` seems generally safe when the `--only-missing` flags is set
- installing Gateway APIs in `install control-plane` seems fragile, since there's no `--only-missing` option and the Gateway CRDs might already be present. IIUC, you normally handle this in helm by putting the CRDs in a separate chart.

**Comment by michaelbeaumont** [comment]
> - should we make this conditional on the gateway build flags?

I think so, as long as the flag exists.

> - installing Gateway APIs in `install control-plane` seems fragile, since there's no `--only-missing` option and the Gateway CRDs might already be present. IIUC, you normally handle this in helm by putting the CRDs in a separate chart.

It's a good point and IMO if we make it anything but completely automatic (by checking if the CRDs are already present), there's no reason not to just use the upstream install method (i.e. `kustomize`)

> - or should we have a CLI flag to toggle it (instead of, or in addition to the build flag)?

Yes, for once the build flag is gone.

**Comment by jpeach** [comment]
@michaelbeaumont So what I'm thinking here is that we have a separate command to install the gateway controller (including CRDs and so forth). This is per the discussion in the doc. I think that this one step install is more straight forward than adding options to the kuma control plane install,help chart and so on. However, your controller PR is bundling the gateway controller into kuma-cp, so we need to choose how this is all going to install and work :)

**Comment by michaelbeaumont** [comment]
In draft until we've figured out how exactly we use Gateways _without_ Gateway API. See #3427

**Comment by lahabana** [comment]
@michaelbeaumont what should we do about this in the end? Last time we chatted we said the gatewayAPI should be installed by itself?

**Comment by michaelbeaumont** [comment]
I think we can probably close this for now, we can always resurrect it. I think we decided that we do want to think about what builtin install experience we can offer but it's easy enough to install Gateway API from upstream for now.

**Comment by lahabana** [comment]
@jakubdyszkiewicz deal with this PR as you are looking into this

**Comment by jakubdyszkiewicz** [comment]
Closing for now. xref #3702

**Pull request closed without merging**
