### PR TITLE
chore(deps) improve developer tool downloading

### PR DESCRIPTION
**Pull request by jpeach**
### Summary

* Use consistent curl options when downloading developer tools
* Install helm into the CI tools directory rather than the default of /usr/local
* Fix the download location for kustomize, which appears to have changed over time.

### Full changelog

N/A

### Issues resolved

N/A

### Documentation

N/A

### Testing

- [x] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes

### CODE REVIEW

**Comment by jakubdyszkiewicz** [comment]
Hey, we don't have `/retest` command. You need to go to CircleCI and click `rerun from failed`. I rerun this for you.

**Review by jakubdyszkiewicz — APPROVED** [review]

**Comment by jpeach** [comment]
> Hey, we don't have `/retest` command. You need to go to CircleCI and click `rerun from failed`. I rerun this for you.

Ah I see it. It's not available for me to click though, maybe I need more karma to do that?

**Review by nickolaev — APPROVED** [review]

**Comment by jakubdyszkiewicz** [comment]
What fails is an e2e test that @lobkovilya fixed in other PR.

**Pull request merged**
