### PR TITLE
fix(install): use bitnami/kubectl image for helm hooks

### LINKED ISSUE #6326: Review which kubectl image to use in Helm hooks
### Description

If we still need them can we use an already existing kubectl image instead of building one. If yes let's remove `tools/kubectl`

### PR DESCRIPTION
**Pull request by lahabana**
Fix #6326

### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues --
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --
- [x] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by lahabana** [comment]
I think one inconvenient of this is that dependabot won't catch it. I think we need to inline the 3 parts to do this.

**Comment by bartsmykla** [comment]
@lahabana what do you mean by:
> I think we need to inline the 3 parts to do this.

**Review by michaelbeaumont — COMMENTED** [review]
I think we can remove `tools/kubectl` then, right?

**Comment by lahabana** [comment]
> I think we can remove tools/kubectl then, right?

Yes and just did it

**Comment by lahabana** [comment]
Finally works @slonka

**Review by slonka — APPROVED** [review]

**Pull request merged**
