### PR TITLE
feat(xds): filter-chain builder constructor require name

### PR DESCRIPTION
**Pull request by mmorel-35**
Replaces FilterChainNameConfigurer with the addition of the name as constructor argument for FilterChainBuilder.

### Checklist prior to review

- [ ] [Link to relevant issue][1] as well as docs and UI issues -- #2538
- [ ] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Tests (Unit test, E2E tests, manual test on universal and k8s) --
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [ ] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by bartsmykla** [comment]
I'm not sure, but I think this PR description is a little bit misleading. Constructors now expect a name as a second parameter, but we are not checking if the name is not empty. I would say that we should maybe require the non empty name here (even if envoy allows empty name in filter-chains)?

@jakubdyszkiewicz wdyt?

**Comment by mmorel-35** [comment]
It would be nice to require a name but right now only a few filter chains has a name so I just modified the builder interface to make it visible. 
To make the name mandatory, the naming logic needs to be implemented first

**Comment by bartsmykla** [comment]
@mmorel-35 after https://github.com/kumahq/kuma/pull/7105 landed, could you update this PR?

**Comment by lobkovilya** [comment]
@mmorel-35 could you please introduce a string const:
```go
const AnonymousResource = ""
```
and pass it to every FilterChainBuilder that doesn't have a name yet. So in the future when we want to get rid of all anonymous resources (to close #2538) we could simply search for usage of this const.

**Comment by mmorel-35** [comment]
Hi @lobkovilya ,
It's done :) !

**Review by bartsmykla — APPROVED** [review]

**Pull request merged**
