### PR TITLE
Improved validation of listener generation

### LINKED ISSUE #797: Improve validation of resources before sending them to DP
#### Listeners

Since we are generating listeners in couple of places (InboundProxyGenerator, OutboundProxyGenerator, DirectAccessProxyGeneration, PrometheusEndpointGenerator etc.)
we should double-check if listeners are actually unique (PORT:IP) before sending them to Envoy

#### Proto validation

All envoy resources expose `Validate()` method. We should execute before sending them to DP, just in case.

### PR DESCRIPTION
**Pull request by tharun208**
Signed-off-by: Tharun <rajendrantharun@live.com>

### Validated envoy resources.

SUMMARY_GOES_HERE

### Full changelog

* [Implement ...]
* [Fix..]

### Issues resolved

Fix #797

### Documentation

- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)

### CODE REVIEW

**Review by nickolaev — APPROVED** [review]

**Comment by tharun208** [comment]
@nickolaev validation of the listener's address is still pending. I will add it.

**Review by jakubdyszkiewicz — CHANGES_REQUESTED** [review]
Can we take more general approach and validate are resources that we generate? I'd like to do it in once place so we don't spread this validation logic.

**Comment by nickolaev** [comment]
Is this PR still considered? @tharun208 @jakubdyszkiewicz

**Comment by tharun208** [comment]
can we have the validation logic inside `resource_generator.go` @jakubdyszkiewicz?

**Comment by nickolaev** [comment]
@tharun208 is this one still relevant?

**Comment by tharun208** [comment]
@nickolaev I will close this and comes with a new one after figuring out how to do this

**Pull request closed without merging**
