### PR TITLE
ci(e2e): simplify the way we run e2e tests by using ginkgo directly

### PR DESCRIPTION
**Pull request by lahabana**
### Summary

- Use ginkgo and the possibility to add flags to the ginkgo command line
- Collapse all `_test.go` in the `suite_test.go`

The goal with this is to be able to simplify reusing e2e tests in places that may depend on them.

### Testing

- [ ] Unit tests
- [x] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes

### CODE REVIEW

**Review by jpeach — APPROVED** [review]
LGTM.

Suggest that `collect` of `client` might be a better package name for the testutils Collect API.

**Review by bartsmykla — APPROVED** [review]
lgtm

**Review by lobkovilya — APPROVED** [review]

**Review by jakubdyszkiewicz — APPROVED** [review]

**Comment by lahabana** [comment]
Btw this is not cold. I just know it will break KongMesh so I'm just waiting to have enough time ahead of me to fix KM as soon as I merge this :)

**Comment by lahabana** [comment]
@mergifyio update

**Pull request merged**
