### PR TITLE
feat(kuma-cp) add support for gRPC health checks

### PR DESCRIPTION
**Pull request by chinmaygupta28**
### Summary

SUMMARY_GOES_HERE

### Full changelog

* [Implement ...]
* [Fix ...]

### Issues resolved

Fix #XXX

### Documentation

- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)

### Testing

- [ ] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes 

### Backwards compatibility

- [ ] Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.

### CODE REVIEW

**Comment by lahabana** [comment]
xref https://github.com/kumahq/kuma/issues/3039

**Comment by lahabana** [comment]
@chinmaygupta28 is this something you are planning to keep working on?

**Comment by chinmaygupta28** [comment]
@lahabana yes, will wrap this up, for the time being I had made use of proxy template and hence was depriortised for my workflow but since I had already made progress I can wrap it up in a week's time.

**Comment by lahabana** [comment]
@chinmaygupta28 still working on this? Seems like not very much is missing to make this work

**Pull request closed without merging**
