### PR TITLE
chore(*) enable helm chart release in CI

### PR DESCRIPTION
**Pull request by nickolaev**
Re-enable Helm Chart releasing as a part of the CI release job.

### CODE REVIEW

**Review by austince — APPROVED** [review]
Looks good to me! We should continue the discussion in #1105 at some point as well -- we may run into issues trying to sync releases of the chart and Kuma itself.

**Comment by jakubdyszkiewicz** [comment]
Yeah, so my main concern here is how do we handle the following scenarios
1) What if for some reason we need to "rerelease" Kuma? Technically after putting a tag we can still remove tag, remove binaries and release again. In other words, what is the behavior when we are trying to publish a HELM chart that is already published?
2) We release RC, we don't want to release a chart (actually we want, but it should be clear it's RC), how do we handle that?
3) The same about "previews" that we occasionally released a couple of times.

I'd love to merge it, but I think we need to agree on the versioning of charts before we do it.

**Comment by austince** [comment]
>     1. What if for some reason we need to "rerelease" Kuma? Technically after putting a tag we can still remove tag, remove binaries and release again. In other words, what is the behavior when we are trying to publish a HELM chart that is already published?

I think we might be able to edit the chart repo's [index.yaml](https://github.com/kumahq/charts/blob/gh-pages/index.yaml) file, though other services may cache this. Is this something we would only want to do in "extreme" circumstances, or does this happen regularly?
 
>     2. We release RC, we don't want to release a chart (actually we want, but it should be clear it's RC), how do we handle that?
>     3. The same about "previews" that we occasionally released a couple of times.

How does the git flow work for these RCs? Is it always released from master or is a new branch cut like the other release-x.x branches? We could probably support these cases by releasing the charts via a separate tag than kuma itself (i.e. release on `chart-x.y.z` tags only) but this would clutter the GitHub releases page (which may be ok?).

**Comment by nickolaev** [comment]
> Yeah, so my main concern here is how do we handle the following scenarios
> 
> 1. What if for some reason we need to "rerelease" Kuma? Technically after putting a tag we can still remove tag, remove binaries and release again. In other words, what is the behavior when we are trying to publish a HELM chart that is already published?

But this can potentially happen even after we release the Helm charts manually 

> 2. We release RC, we don't want to release a chart (actually we want, but it should be clear it's RC), how do we handle that?

We can introduce a filter on this, so we only do helm when the tag is ([0-9]*)\.([0-9]*)\.([0-9]*)

> 3. The same about "previews" that we occasionally released a couple of times.

Same.
 
> I'd love to merge it, but I think we need to agree on the versioning of charts before we do it.

**Pull request merged**
