### PR TITLE
feat(helm): add resource limits option for control plane deployment

### PR DESCRIPTION
**Pull request by gdasson**
**Summary**

Currently, there is no place to specify the resource limits for
control plane deployment. This PR provides the option to specify
limits for control plane deployment

**Full changelog**

Helm - Provided resource limits option for kuma-cp deployment

**Testing**
- [ ] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [X] Manual testing on Kubernetes

**Backwards compatibility**

Does not effect backwards compatibility.

Signed-off-by: Gaurav Dasson <gaurav.dasson@gmail.com>

### CODE REVIEW

**Comment by gdasson** [comment]
@johnharris85 : Please review. Thanks!

**Comment by gdasson** [comment]
@jakubdyszkiewicz , @johnharris85 : Closed the old PR and opened a new one. Not sure why these tests are failing: [test/e2e-ipv4](https://circleci.com/gh/kumahq/kuma/140465?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

**Comment by lahabana** [comment]
@mergifyio update

**Comment by lahabana** [comment]
@gdasson the CI was broken and it got fixed today. I updated your PR to merge with master it should now pass

**Comment by johnharris85** [comment]
I'm not generally in favor of setting limits to a different value to requests because it results in unpredictable behavior (especially w.r.t memory). Thoughts from other folks?

Other than that, LGTM.

**Comment by jakubdyszkiewicz** [comment]
Agree with @johnharris85
Also, setting the limit by default would be a breaking change.

**Comment by gdasson** [comment]
@johnharris85 , @lahabana , @jakubdyszkiewicz : Removed the defaults section for limits. Will only be included in deployment spec if explicitly set by user in values.yaml. Please review. Thanks!

**Comment by jakubdyszkiewicz** [comment]
Thanks for iterating on this one.

Correct me if I'm wrong, but in the end, it was possible to specify limits, but it was a string value, now it's an object.
The object is more convenient, that's for sure, but it is a breaking change in the chart.

@lahabana should we merge it and put information in the upgrade guide?

**Comment by lahabana** [comment]
I think it's acceptable especially as the chart version is going to be changed to be insync with kuma versions

**Review by lahabana — APPROVED** [review]

**Comment by lahabana** [comment]
@gdasson 

If you can add a commit with:

```diff
diff --git a/UPGRADE.md b/UPGRADE.md
index fd7465cbd..8b1e80a8b 100644
--- a/UPGRADE.md
+++ b/UPGRADE.md
@@ -8,6 +8,10 @@ does not have any particular instructions.

 ## Upcoming release

+### Helm
+
+controlPlane.resources is now on object instead of a string. Any existing value should be adapted accordingly.
+
 ### Zone egress

 Previously, when mTLS was configured and `ZoneEgress` deployed, requests were routed automatically through `ZoneEgress`. Now it's required to
```

We'll merge this

**Comment by gdasson** [comment]
@lahabana : I got a bit lazy and updated the UPDATE.md file within GitHub web. Somehow it's messing up the DCO now. Any suggestions to fix other than rebasing? Apologies, I am making rookie mistakes, I am a new contributor..

**Comment by lahabana** [comment]
@gdasson  it's fine I can fix this on merge :)

**Comment by michaelgoodrx** [comment]
Hi @lahabana @gdasson, I think I found a couple problems with this PR.

 - The change log doesn't make sense. `controlPlane.resources` was already an object, it was never a string.
 - You could have set the limits already without this PR by just doing something like
   ```
    resources:
      limits:
        cpu: ...
   ```
 - This is a unnecessary breaking change because previously, someone could have `resources:` set to a null value in their `values.yaml` and they'd get the defaults, whereas now installation will fail because the condition in the if statement tries to access `resources.requests` which won't exist. It's common for people to copy the default `values.yaml` before customizing stuff, so many people may have `resources:` set to a null value.

**Comment by lahabana** [comment]
Wasn't the point of this PR to be able to set limits without changing the default requests? I'm not sure this was possible without this.

You are right about this being a breaking change and that's why the change was documented in `UPGRADE.md` no?

I believe keeping the default request while setting a limit is an ok use-case don't you think?

**Comment by michaelgoodrx** [comment]
Gotcha, if that is the point of the PR then yes it makes sense.

**Pull request merged**
