### PR TITLE
chore(*) add initial gateway plugin structure

### PR DESCRIPTION
**Pull request by jpeach**
### Summary

Add a skeleton gateway plugin that can be enabled by a build-time
feature flag. It is always enabled for tests, but disabled by default
for other builds.
    
Stub out some structure for Kuma gateway profile generators. We expect
to need a listener generator and a route generator and it probably make
sense to separate them.

Depends on (and is rebased on) #2404 and #2394.

### Full changelog

N/A

### Issues resolved

N/A

### Documentation

N/A

### Testing

- [x] Unit tests
- [x] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes 

### Backwards compatibility

- [x] Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.

### CODE REVIEW

**Comment by jpeach** [comment]
This still depends on #2404, but can be reviewed now. I'll rebase once #2404 lands.

**Comment by jpeach** [comment]
> This still depends on #2404, but can be reviewed now. I'll rebase once #2404 lands.

Rebased.

**Review by lobkovilya — APPROVED** [review]
Looks great! We definitely need `BuildResourceSet` for other generators :)

**Comment by jpeach** [comment]
> Looks great! We definitely need `BuildResourceSet` for other generators :)

Maybe we should hoist that up and make a refactoring pass.

**Pull request merged**
