### PR TITLE
fix(policy): don't set empty kuma.io service when using MeshHTTPRoute

### PR DESCRIPTION
**Pull request by lukidzi**
#### Problem
When policy targets `MeshHTTPRoute` with `to.kind: Mesh` we are creating an artificial object that has a tag with a hashed value of a matcher from `MeshHTTPRoute`. By default, we are creating it as a `MeshServiceSubset` which by default has `kuma.io/service` with an empty value. That works well for policies that have `to.kind: MeshService/MeshServiceSubset` but not for `Mesh/MeshSubset`. Later we cannot match the subset because `kuma.io/service: ""` is set. This change checks the kind and sets the correct value.

The best to review by commits 
1st shows the issue
2nd implementation
3rd shows the file

- [ ] [Link to relevant issue][1] as well as docs and UI issues --
- [ ] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by lukidzi** [comment]
When `kuma.io/service` is empty string we cannot match policies. When doing `isSubset` we are trying to find `kuma.io/service: ""` but in case if targetRef `Mesh` we don't have `kuma.io/service` label

**Review by michaelbeaumont — APPROVED** [review]
OK I guess it isn't clear to me whether this is a user-visible problem?

**Comment by lukidzi** [comment]
I think it could be visible when targeting `MeshHTTPRoute` with `to.Kind: Mesh` because we wouldn't be able to match

**Comment by lukidzi** [comment]
Ok so it isn't an issue with the MeshTimeout policy because MeshHTTPRoute for sidecar (not gateway) doesn't accept MeshHTTPRoute `to.kind: Mesh` which is a root of the issue

**Pull request merged**
