### PR TITLE
chore(kuma-cp) annotate required fields in protos

### PR DESCRIPTION
**Pull request by bartsmykla**
### Summary

These fields will be used to mark fields as required in our docs
when generated

### Issues resolved

No issue

### Documentation

No documentation changes

### Testing

- [ ] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes 

### Backwards compatibility

- [x] Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.

### CODE REVIEW

**Comment by jpeach** [comment]
How do we keep this in sync with the actual validation code?

**Comment by bartsmykla** [comment]
@jpeach without automating generation of validators I don't think it will be easy, so probably currently doing it manually will have to be sufficient, or we have to take time to automate validators

**Comment by jpeach** [comment]
> @jpeach without automating generation of validators I don't think it will be easy, so probably currently doing it manually will have to be sufficient, or we have to take time to automate validators

Yeh we could look at protoc-gen-validate again I suppose :shrug:

**Review by jpeach — APPROVED** [review]
This looks reasonable to me, with the caveat that I didn't double-check everything against the code :)

**Pull request merged**
