### PR TITLE
ci(gha): enable self hosted runners for arm64 e2e tasks

### PR DESCRIPTION
**Pull request by jijiechen**
### Checklist prior to review

Please merge this PR only after you see the self hosted runners shared by the org level on this page:
https://github.com/kumahq/kuma/settings/actions/runners

- [x] [Link to relevant issue][1] as well as docs and UI issues
  - fixes https://github.com/kumahq/kuma/issues/10583
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS 
  - Should not impact
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) 
  - Manual tested
  - [x] Don't forget `ci/` labels to run additional/fewer tests
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? 
  - No
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) 
  - No

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by jakubdyszkiewicz** [comment]
I see them! But the status is offline. Is that expected?
image

**Comment by jijiechen** [comment]
@jakubdyszkiewicz The offline ones are incorrect. I removed them and now we can see the ones shared from org level.
We can merge this PR safely now.

**Review by jakubdyszkiewicz — APPROVED** [review]

**Comment by lahabana** [comment]
@jijiechen we should backport this to all other branches to stop using circleci everywhere

**Comment by jijiechen** [comment]
Got it, let me create another PR to get it backported.

**Pull request merged**
