### PR TITLE
Add more recognizable plane identifier in DiscoveryResponse

### LINKED ISSUE #1011: Add control plane identifier in DiscoveryResponse
### Summary

1) We should generate more recognizable Control Plane InstanceID (like `hostname-${4 random chars}` not random `UUID`)
2) `DiscoveryResponse` contains Control Plane Identifier that we should fill this info in the control plane.
3) We can then build a pane in `Kuma Dataplane` dashboard to which CP Instance the DP is connected which will help with debugging.

### PR DESCRIPTION
**Pull request by jewertow**
### Summary

Replace random UUID with hostname and 4 random characters in `DiscoverResponse.ControlPlane.Identifier`.

### Issues resolved

Fix #1011

### CODE REVIEW

**Review by jakubdyszkiewicz — COMMENTED** [review]
Hey @jewertow 

thanks for contributing. A couple of pointers - do not touch KDS, it's meant for Control Plane <-> Control Plane communication.

What we want to achieve here is that the Dataplane will know about Control Plane instance. Look for DiscoveryResponse object, and ControlPlane field.
I see there is no way to pass this information to go-control-plane which is in charge of creating this object. The solution would be to create implementation of `github.com/envoyproxy/go-control-plane/pkg/server/v2#Callbacks` and set this with `OnStreamResponse` since you can modify this object there.

**Comment by jewertow** [comment]
@jakubdyszkiewicz 
Thank you for the code review and explanation. 
I will investigate Kuma's architecture more and come back to this issue next week.

**Comment by jewertow** [comment]
I will come back to this PR soon.

**Comment by jewertow** [comment]
@jakubdyszkiewicz 
There are already several implementations of `Callbacks` interface, but in my opinion none of them fit well for this case.
Can I add another implementation dedicated for this case or should I add this feature to one of existing implementations?
What do you think?

**Pull request closed without merging**
