### PR TITLE
feat(kuma-cp): set `kuma.io/mesh` on universal resource labels

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues -- Closes https://github.com/kumahq/kuma/issues/11036
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Review by Icarus9913 — APPROVED** [review]

**Comment by Icarus9913** [comment]
Just one considering:
Do we need to supplement the KDS mapper function to update this label?


https://github.com/kumahq/kuma/blob/e5d62a7b9180a244a27a80421e567ebb78f2a6ae/pkg/kds/context/context.go#L70-L71

https://github.com/kumahq/kuma/blob/e5d62a7b9180a244a27a80421e567ebb78f2a6ae/pkg/kds/context/context.go#L94-L98

**Review by jakubdyszkiewicz — APPROVED** [review]
I'm slightly anxious about this change.
It means that it's duplicated (field + label), not sure if that won't confuse users. For example they will try to set mesh by label on universal which is not what they should do. 

Maybe we need a validation that if they put a resource, mesh label cannot be different than mesh field.

**Comment by michaelbeaumont** [comment]
> Maybe we need a validation that if they put a resource, mesh label cannot be different than mesh field.

I wonder if maybe the label shouldn't be settable at all? So that there's no confusion around the fact that the label isn't the source of truth

**Comment by jakubdyszkiewicz** [comment]
> I wonder if maybe the label shouldn't be settable at all? So that there's no confusion around the fact that the label isn't the source of truth

Maybe, but someone could take a YAML from the GUI (or export!), try to apply it and it would fail with validation, because label exist

**Review by jakubdyszkiewicz — APPROVED** [review]

**Pull request merged**
