### PR TITLE
ci(k8s): don't ignore errors on docker network create

### PR DESCRIPTION
**Pull request by michaelbeaumont**
## Motivation

We weren't exiting with an error if `docker network create` failed.

## Implementation information

Avoid repeating the network handling logic by using a Makefile variable.

### CODE REVIEW

**Comment by lahabana** [comment]
Maybe we just don't need the flock and there's a better way to do this...

**Review by slonka — APPROVED** [review]
> Maybe we just don't need the flock and there's a better way to do this...

I'd say this is be than before so we can create an issue about flock and merge this

**Review by jijiechen — APPROVED** [review]

**Comment by lahabana** [comment]
I think someone agrees that flock is wrong (I'm the one who introduced this :) ): https://stackoverflow.com/a/59724999 :) 

I think [order only prerequisite](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html) would enable us to drop the flock altogether. Let me try a PR :)

**Comment by michaelbeaumont** [comment]
> I think [order only prerequisite](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html) would enable us to drop the flock altogether. Let me try a PR :)

When I opened this PR I knew 50/50 either approved or trigger @lahabana to come up with some make magic :slightly_smiling_face:

**Comment by michaelbeaumont** [comment]
@lahabana im gonna merge this for now cause I think it marginally improves things

**Pull request merged**
