### PR TITLE
feat: support selectively enabling Pods 

### PR DESCRIPTION
**Pull request by lobkovilya**
### Summary

Today we have an ability to enable sidecar-injection for the whole Namespace and disable on particular pods. There is a desire to be able to do vice-versa - disable for the whole Namespace and enable on some specific pods. 

Also today we can specify Mesh only for the Pod, but we want to have an ability to specify Mesh in Namespace (for each Pod in it).

That PR adds that functionality. But there are some caveats that probably should be discussed: 
 - injector used to receive Pods only from Namespaces that match `kuma.io/sidecar-injection: enabled`. But since we want to override that behavior in Pod, now the injector receives all Pods from all Namespaces regardless of labels. 
 - there is an asymmetry in Labels vs Annotations usage. Namespaces utilize Labels but Pods utilize Annotations. Preferably would be to use Annotation in both Namespaces and Pods, but that's breaking change for the Namespace format. So the question, do we want to use Annotations in Namespace?

### Documentation

- [x] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/244)

### CODE REVIEW

**Comment by subnetmarco** [comment]
This is a breaking change, needs to be released in `0.6.x`.

**Comment by jakubdyszkiewicz** [comment]
I'm confused, so Kuma becomes opt-out instead of opt-in?

As a Mesh operator in a company that has 100 000 of workloads, I'd like to test Kuma first on a small chunk of my infrastructure (one namespace). How can I do it?

**Comment by lobkovilya** [comment]
@jakubdyszkiewicz all behavior that we have today won't be changed. You still can annotate Namespace with `kuma.io/sidecar-injection: enabled` and sidecars will be injected to every pod in that Namespace. 
That PR gives an ability to omit `kuma.io/sidecar-injection` in Namespace and set it only for couple Pods in that Namespace.

**Comment by jakubdyszkiewicz** [comment]
I'm sorry, I got a wrong impression from the PR description.

Then this looks good to me, but I'm still thinking about labels vs annotations. What is the reason to pick annotations?

**Comment by lobkovilya** [comment]
The main reason is to have the same way of setting things on Namespace and Pods. I think it might confuse people that `kuma.io/sidecar-injection` is a label on Namespaces and annotation on Pods. But looks like we can't set Labels on Pods because Labels are converted to Dataplane's Tags and we probably don't want to have `kuma.io/sidecar-injection` as a tag. And according to k8s documentation Labels serves for identifying info, you can query resources based on Labels. That's why I think it makes sense to leverage Kuma using annotations.

**Comment by nickolaev** [comment]
@lobkovilya you'll have to merge master to resolve the confilcts.

**Comment by subnetmarco** [comment]
Documentation also needs to be updated.

**Comment by nickolaev** [comment]
After a discussion with @jakubdyszkiewicz, we agreed that the proposed approach int he PR is valid and we can go ahead t merge it once 0.5.1 is released.
@lobkovilya please make sure to rebase after the release.

**Comment by subnetmarco** [comment]
Everything is a `label`. We are open to revisit this in the future.

**Pull request merged**
