### PR TITLE
feat(kuma-cp) add affinity to CP and Ingress PODs

### LINKED ISSUE #3031: Helm chart does not have an option to configure AntiAffinity
### Summary
Hi, for the K8S HA with the cluster having multiple nodes and spread across multiple zones it would be nice to have an option to setup AntiAffinity as otherwise there is a high risk of all the control plane PODs occupying the same node. If this happens then application (new or restarted) won't get a sidecar injected as there is no control plane present at the given moment of time.

### PR DESCRIPTION
**Pull request by andrey-dubnik**
This fixes #3031

### CODE REVIEW

**Comment by jpeach** [comment]
@andrey-dubnik a few questions on this approach

* should kuma-cp include a "soft" anti-affinity configuration by default?
* are there [conventions](https://docs.bitnami.com/tutorials/assign-pod-nodes-helm-affinity-rules/) around this in the helm chart community?

**Comment by andrey-dubnik** [comment]
Yes, soft anti-affinity would be the preferred default but for the true HA affinity should be the hard rule which makes it only 1 pod per the node which might be too restrictive in the scenario where the control plane needs to scale beyond the number of nodes. Unfortunately for the control plane the app label is dynamic so setting the rule via values is problematic so it either changing the label to static and having a default or letting the helm user to write own affinity rule leaving the default empty.

**Comment by jpeach** [comment]
> Unfortunately for the control plane the app label is dynamic so setting the rule via values is problematic

Do you mean the `kuma.selectorLabels`? It's not that clear to me what that's for, but I think that just using the `app` label is probably good enough for affinity?

If the labels are unpredictably dynamic, that makes me wonder how people would reasonably know what to use to set the whole affinity stanza themselves.

**Comment by andrey-dubnik** [comment]
I mean this one - https://github.com/kumahq/kuma/blob/1f507fd10de8299fae0d740d664979de42688a4b/deployments/charts/kuma/templates/cp-deployment.yaml#L18

```
matchLabels:
      {{- include "kuma.selectorLabels" . | nindent 6 }}
      app: {{ include "kuma.name" . }}-control-plane

```

Affinity rule has to have a label filter which is computed during the chart templating which make it possible to write the affinity rule in the values knowing the name of the deployment June is going to have but does not make it straight forward to write a default rule defined in the helm values. 

Default can be written directly in the template with the option to override if affinity value is provided. I can update the PR with default rules in the template files and added logic to accept affinity override if provided via values if this helps?

**Comment by jpeach** [comment]
> Default can be written directly in the template with the option to override if affinity value is provided. I can update the PR with default rules in the template files and added logic to accept affinity override if provided via values if this helps?

Yeh, it sounds to me like soft anti-affinity is the right default, and we should let people override this if they need to, as per your PR here.

**Review by jpeach — APPROVED** [review]
This looks great to me @andrey-dubnik! I'll wait a couple of days to give other people a change to give feedback, then merge.

**Comment by lahabana** [comment]
This looks good thanks @andrey-dubnik! Seems like you might want to update the PR though!

**Comment by jpeach** [comment]
Thanks @andrey-dubnik :+1:

**Pull request merged**
