### PR TITLE
kuma-cp: add OpenAPI description of the Kuma REST API

### LINKED ISSUE #318: Provide an OpenAPI specification for the Kuma HTTP API
In order to be consumable by third-party clients.

### PR DESCRIPTION
**Pull request by yskopets**
### Summary

* add OpenAPI description of the Kuma REST API

### Issues resolved

Fix #318

### CODE REVIEW

**Comment by yskopets** [comment]
@rohgoyal Hey!

Let's continue work on a `OpenAPI` descriptor in this PR.

I've merged the changes you prepared in it and did some refactoring after that:
- moved files into `pkg/api-server/data` folder
- converted format to `v3`
- refactored structure of the descriptor
- completed description of `/meshes` API (with data types(placeholders), requests, responses, examples, etc)
- completed description of `/dataplanes` API (with data types(placeholders), requests, responses, examples, etc)

Please go ahead and complete description of the remaining APIs.

Thanks again for your interest in Kuma! 👍

**Comment by subnetmarco** [comment]
What is the status of this PR?

**Comment by yskopets** [comment]
@subnetmarco I know that @rohgoyal is working on it.

**Comment by jakubdyszkiewicz** [comment]
Closing due to no activity. We can reopen if needed. It requires substantial updates due to API changes for the last 1,5y.

**Pull request closed without merging**
