### PR TITLE
feat(kuma-cp): enable traffic route for inspect endpoints

### LINKED ISSUE #3718: Tools for visibility: add support for ProxyTemplate
### Description

Today there is no support in API for ProxyTemplate

### PR DESCRIPTION
**Pull request by tharun208**
### Summary

Based on #3462 

This PR introduces `traffic-route` policies to inspect policies endpoints.

### Full changelog

* [Implement ...]
* [Fix ...]

### Issues resolved

Partially Fix #3718

### Documentation

- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)

### Testing

- [x] Unit tests
- [ ] E2E tests
- [x] Manual testing on Universal
- [ ] Manual testing on Kubernetes

### Backwards compatibility

- [ ] Update [`UPGRADE.md`](/UPGRADE.md) with any steps users will need to take when upgrading.
- [ ] Add `backport-to-stable` label if the code follows our [backporting policy](/CONTRIBUTING.md#backporting)

### CODE REVIEW

**Comment by lobkovilya** [comment]
@tharun208 by default it's not added as an HTTP endpoint, you also have to add 
```
option (kuma.mesh.resource).allow_to_inspect = true;
```
to the `traffic_route.proto`

**Comment by tharun208** [comment]
@lobkovilya 

> @tharun208 by default it's not added as an HTTP endpoint, you also have to add
> 
> ```
> option (kuma.mesh.resource).allow_to_inspect = true;
> ```
> 
> to the `traffic_route.proto`

Thanks, @lobkovilya, I thought of doing for `/meshes/traffic-routes/{name}/dataplanes` as a separate PR. But, agree that we can add the changes for the above endpoint in this same pr.

**Comment by lobkovilya** [comment]
Thank you @tharun208, yes I think it's easier to do in a single PR. Could you please also add a test entry for TrafficRoute here https://github.com/kumahq/kuma/blob/master/pkg/api-server/inspect_endpoints_test.go#L504?

**Comment by tharun208** [comment]
@lobkovilya thanks and added the test

**Review by lobkovilya — APPROVED** [review]

**Pull request merged**
