### PR TITLE
feat(kuma-cp): add a dedicated health endpoint

### PR DESCRIPTION
**Pull request by wheelerlaw**
### Checklist prior to review

Proposed change to add a dedicated health endpoint to serve health information about the CP. Related to Kong/mink-charts#120. 

- [ ] [Link to relevant issue][1] as well as docs and UI issues --
- [ ] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Tests (Unit test, E2E tests, manual test on universal and k8s) --
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [ ] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Review by jakubdyszkiewicz — COMMENTED** [review]
We do have health endpoint on diagnostic server `:5680`
https://github.com/kumahq/kuma/blob/master/pkg/diagnostics/server.go#L42

Do we need another one on API Server?

**Comment by wheelerlaw** [comment]
> We do have health endpoint on diagnostic server `:5680` [`master`/pkg/diagnostics/server.go#L42](https://github.com/kumahq/kuma/blob/master/pkg/diagnostics/server.go?rgh-link-date=2023-03-07T08%3A55%3A49Z#L42)
> 
> Do we need another one on API Server?

While it is a dedicated endpoint, it does not look like it returns a JSON object with service information. Also, is it meant to be run in production?

**Comment by slonka** [comment]
> Also, is it meant to be run in production?

yeah I think it's fine to run in production, there are toggles to turn off sensitive endpoints for debugging

**Comment by wheelerlaw** [comment]
> > Do we need another one on API Server?
> 
> I don't see a "port" in a route configuration - [docs.konghq.com/gateway/latest/admin-api/#request-body-3](https://docs.konghq.com/gateway/latest/admin-api/#request-body-3) so I don't think a single service can serve multiple ports.

Hmm, I think we can do some k8s + kgateway magic here to get this running on the diagnostic server. The existing health endpoint on the diagnostic server won't be enough as it is though, we need service information in the form of JSON, which it looks like the health endpoint @jakubdyszkiewicz mentioned only returns a 200.

**Comment by slonka** [comment]
I haven't got a response here https://github.com/Kong/kgateway/pull/267#issuecomment-1468013162 and no one was strongly against this on slack I'm merging this as it is.

**Review by slonka — APPROVED** [review]

**Pull request merged**
