### PR TITLE
ci: use "ref_name" instead of "refName" in GH action

### PR DESCRIPTION
**Pull request by lobkovilya**
Signed-off-by: Ilya Lobkov <ilya.lobkov@konghq.com>

### Checklist prior to review

- [X] Link to docs PR or issue --
- [X] Link to UI issue or PR --
- [X] Is the [issue worked on linked][1]? --
- [X] The PR does not hardcode values that might break projects that depend on kuma (e.g. "kumahq" as a image registry) --
- [X] The PR will work for both Linux and Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [X] Unit Tests --
- [X] E2E Tests --
- [X] Manual Universal Tests --
- [X] Manual Kubernetes Tests --
- [X] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [X] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? -- Yes
- [X] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Review by Automaat — CHANGES_REQUESTED** [review]
this is based on old branch, we cannot merge it like this

**Comment by slonka** [comment]
> this is based on old branch, we cannot merge it like this

why did we rewrite history on release-2.1?

**Comment by lobkovilya** [comment]
@Automaat I updated the branch

**Review by Automaat — APPROVED** [review]

**Comment by slonka** [comment]
For the future GH actions are always run from main branch so we should branch off from them.

**Comment by lobkovilya** [comment]
@Mergifyio backport release-2.0 release-1.8 release-1.7 release-1.6 release-1.5

**Pull request merged**
