### PR TITLE
fix(policy): apply defaults for MeshTimeout when from or to section i…

### PR DESCRIPTION
**Pull request by Automaat**
Fixes: #5850

### Checklist prior to review

- [x] Link to docs PR or issue --
- [x] Link to UI issue or PR --
- [x] Is the [issue worked on linked][1]? --
- [x] The PR does not hardcode values that might break projects that depend on kuma (e.g. "kumahq" as a image registry) --
- [x] The PR will work for both Linux and Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Unit Tests --
- [x] E2E Tests --
- [x] Manual Universal Tests --
- [x] Manual Kubernetes Tests --
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [x] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Review by lukidzi — APPROVED** [review]

**Comment by lukidzi** [comment]
Just ensure that order in snapshot is stable, and only timeouts values have changed

**Comment by lahabana** [comment]
Also let's make sure these defaults do not get applied if not meshTimeout policy is set (we don't want to change the default behaviour of timeouts everywhere I think)

**Comment by Automaat** [comment]
> Also let's make sure these defaults do not get applied if not meshTimeout policy is set (we don't want to change the default behaviour of timeouts everywhere I think)

That's why I didn't merge it yet I think that they are changed. So this is not that easy fix, and I need more time to fix this. It would be best if this skip this release

**Comment by lahabana** [comment]
Let's make sure we document it for 2.1.x if this skips the release

**Comment by Automaat** [comment]
https://github.com/kumahq/kuma/pull/5902

**Pull request closed without merging**
