### PR TITLE
fix(kuma-dp): only call syscall.Mkfifo for accesslogs on unix-like systems

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Checklist prior to review

- [x] Link to docs PR or issue --
- [x] Link to UI issue or PR --
- [x] Is the [issue worked on linked][1]? --
- [x] Unit Tests --
- [x] E2E Tests --
- [x] Manual Universal Tests --
- [x] Manual Kubernetes Tests --
- [x] Do you need to update [`UPGRADE.md`](/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](/CONTRIBUTING.md#backporting)? --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by lahabana** [comment]
Ho I did #4767  too :( pick whichever approach you prefer

**Review by lahabana — APPROVED** [review]
I'll approve but as I said look at #4767 I find it a little simpler

**Comment by michaelbeaumont** [comment]
Yeah the only real difference is whether or not it errors on Windows. Paul mentioned the old method used unix sockets and didn't work so please pick whichever keeps the same behavior/has the right behavior @lahabana 😀. I don't know/have a strong opinion

**Comment by lahabana** [comment]
I have a small preference for not erroring as you might deploy policies that impact both envs

**Comment by michaelbeaumont** [comment]
Closing for #4767

**Pull request closed without merging**
