### PR TITLE
feat(gateway): cp annotations from gateway to svc

### LINKED ISSUE #4075: Mesh gateway svc - support for additional annotations and loadBalancerIp
### Description

So that a user can have more control over how a cloud load balancer is created for a mesh gateway service, they should be able to specify a loadBalancerIp and additional annotations. These would then get included in the mesh gateway service that is created.

Perhaps something like:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: edge-gateway
spec:
  replicas: 1
  serviceType: LoadBalancer
  loadBalancerIp: 1.2.3.4
  additionalAnnotations:
    annotation1Name: annotation1Value
    annotation2Name: annotation2Value
  tags:
    kuma.io/service: edge-gateway
```

### PR DESCRIPTION
**Pull request by johnharris85**
### Summary

Many cloud providers use annotations on service objects to control behavior with their auto-provisioned load balancers. This PR adds a feature that will copy all annotations specified on the `MeshGatewayInstance` object to the generated service.

In #4075 there was some discussion about how to implement this, and a suggestion that maybe we go down the route of creating a CRD that would allow full customization of the generated service. This makes sense in future, however the 90% use case is solved by just enabling a user to specify annotations. This PR's implementation covers that use case for users who are currently experiencing issues while not adding / altering any CRDs / APIs, and is easy to deprecate when we decide on a 'better' solution.

Will add docs if folks are fine with this implementation.

### Issues resolved

Partially fix #4075 

### Documentation

- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)

### Testing

- [x] Unit tests
- [ ] E2E tests
~- [ ] Manual testing on Universal~
- [x] Manual testing on Kubernetes

### Backwards compatibility

~- [ ] Update [`UPGRADE.md`](/UPGRADE.md) with any steps users will need to take when upgrading.~
~- [ ] Add `backport-to-stable` label if the code follows our [backporting policy](/CONTRIBUTING.md#backporting)~

### CODE REVIEW

**Comment by johnharris85** [comment]
Test failure looks unrelated?

**Comment by michaelbeaumont** [comment]
@johnharris85 What do you think about just adding a single `spec.serviceTemplate.metadata.annotations` field?

**Review by michaelbeaumont — APPROVED** [review]
LGTM maybe @lahabana take a look too :shrug:

**Comment by lahabana** [comment]
Arg obviously my tool is broken with forks :(

**Review by lahabana — APPROVED** [review]
Once the conflict is resolved

**Pull request merged**
