### PR TITLE
fix(conf) fix cp service annotations in helm chart

### LINKED ISSUE #1750: Helm Control Plane Annotations Template Invalid
### Summary

Helm chart template is generating invalid cp service template when modifying annotations.

### Steps To Reproduce

1. Add annotation to .Values.controlPlane.service.annotations
2. Generate the helm template `helm template --debug -n kuma-system kuma-system .`
3. Review the kuma/templates/cp-service.yaml output and you will see the additional incorrect formatting with an extra indent.
```yaml  
annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5680"
      somekey: "somevalue"
```
### Additional Details & Logs

- Version
1.1.1 of the Helm chart
- Error logs
Error: YAML parse error on kuma/templates/cp-service.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key.
- Configuration
```yaml
controlPlane:
  service:
    annotations:
      somekey: somevalue
```
- Platform and Operating System
Reproduced in MacOS and Windows
- Installation Method (Helm, kumactl, AWS CloudFormation, etc.)
Helm

### PR DESCRIPTION
**Pull request by nbrink91**
### Summary

Fix indenting in the Helm chart CP service annotations.

### Full changelog

* Fix indenting for .Values.controlPlane.service.annotations field in the Helm chart.

### Issues resolved

Fix #1750

### CODE REVIEW

**Comment by nickolaev** [comment]
Thanks for your contribution @nbrink91!

**Comment by nickolaev** [comment]
Oh I see it fails, would you mind do the following:
```sh
make generate/kumactl/install/k8s/control-plane
make check
UPDATE_GOLDEN_FILES=true make test
```

And then commit the resulting changes on that branch?

**Comment by nbrink91** [comment]
@nickolaev I'm having some issues getting this to compile. I'm getting the following errors when running `make check`.

diff --git a/go.mod b/go.mod
index af9c2021..c0098cf5 100644
--- a/go.mod
+++ b/go.mod
@@ -24,8 +24,8 @@ require (
        github.com/gruntwork-io/terratest v0.30.15
        github.com/hoisie/mustache v0.0.0-20160804235033-6375acf62c69
        github.com/kelseyhightower/envconfig v1.4.0
-       github.com/kumahq/kuma/api v0.0.0-00010101000000-000000000000
-       github.com/kumahq/kuma/pkg/plugins/resources/k8s/native v0.0.0-00010101000000-000000000000
+       github.com/kumahq/kuma/api v0.0.0-20210402104346-824b8542e3b9
+       github.com/kumahq/kuma/pkg/plugins/resources/k8s/native v0.0.0-20210402104346-824b8542e3b9
        github.com/kumahq/kuma/pkg/transparentproxy/istio v0.0.0-00010101000000-000000000000
        github.com/lib/pq v1.9.0
        github.com/miekg/dns v1.1.40
make: *** [check] Error 1

**Comment by nickolaev** [comment]
Suppressed by #1767

**Pull request closed without merging**
