### PR TITLE
fix(kuma-cp) TLSInspector is causing tcp healthcheck failures

### PR DESCRIPTION
**Pull request by lobkovilya**
### Summary

Just the fact that TLSInspector is configured is causing TCP health checks to fail (mTLS is off)

### Full changelog

* configure TLSInspector only when required

### Issues resolved

N/A

### Documentation

- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)

### Testing

- [ ] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes 

### Backwards compatibility

- [x] Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.

### CODE REVIEW

**Comment by jpeach** [comment]
@lobkovilya Do you understand what's happening here? TLS inspector doesn't do anything except make metadata available, and it looks like it would only break the stream if it thinks it is reading a client hello of > 64k.

**Comment by lobkovilya** [comment]
@jpeach I don't really understand, maybe this is something we have to investigate (could be a bug in envoy), but for now I think we have to merge this for the release because tcp health checks are completely broken

**Comment by jpeach** [comment]
> @jpeach I don't really understand, maybe this is something we have to investigate (could be a bug in envoy), but for now I think we have to merge this for the release because tcp health checks are completely broken

Which tests are failing here? I scrolled a lot but I think I need to pull the logs :-/

**Comment by lobkovilya** [comment]
This PR aims to fix `should mark host as unhealthy if it doesn't reply on health checks`, without this fix it failed in 100 percent cases for me

**Review by jpeach — APPROVED** [review]

**Pull request merged**
