### PR TITLE
fix(kuma-cp): concurrent mesh cache map write

### LINKED ISSUE #5245: kuma-cp concurrent map write
### What happened?

Looks to be at https://github.com/kumahq/kuma/blob/9b2c75323c59daaa0f755dc7b1d7563375cd5fee/pkg/xds/cache/mesh/cache.go#L47

```
fatal error: concurrent map writes

goroutine 917 [running]:
runtime.throw({0x28308fe?, 0x256e840?})
	/home/mike/.local/share/asdf/installs/golang/1.18.5/go/src/runtime/panic.go:992 +0x71 fp=0xc001653608 sp=0xc0016535d8 pc=0x4385d1
runtime.mapassign_faststr(0x235d620, 0xc000e00d20, {0xc00149a690, 0x7})
	/home/mike/.local/share/asdf/installs/golang/1.18.5/go/src/runtime/map_faststr.go:295 +0x38b fp=0xc001653670 sp=0xc001653608 pc=0x4135eb
github.com/kumahq/kuma/pkg/xds/cache/mesh.(*Cache).GetMeshContext.func1({0x346c3f0, 0xc001415bc0}, {0xc0014867c0?, 0x0?})
	/home/mike/projects/kuma/pkg/xds/cache/mesh/cache.go:47 +0x33a fp=0xc001653800 sp=0xc001653670 pc=0x1507d1a
github.com/kumahq/kuma/pkg/xds/cache/once.RetrieverFunc.Call(0xc00000ee30?, {0x346c3f0?, 0xc001415bc0?}, {0xc00149a690?, 0xc00149ede0?})
```

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Checklist prior to review

- [x] Link to docs PR or issue --
- [x] Link to UI issue or PR --
- [x] Is the [issue worked on linked][1]? -- Closes #5245 
- [x] The PR does not hardcode values that might break projects that depend on kuma (e.g. "kumahq" as a image registry) --
- [x] The PR will work for both Linux and Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Unit Tests -- 
- [x] E2E Tests --
- [ ] Manual Universal Tests --
- [ ] Manual Kubernetes Tests --
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [x] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Review by slonka — APPROVED** [review]
Looks alright but we could add a test that concurrently invokes this function and see that `--race` does not complain.

**Review by lahabana — CHANGES_REQUESTED** [review]
There's something odd here! If this is a cache of elements, why do we keep the `latestMeshContext` outside c.cache?

**Comment by michaelbeaumont** [comment]
Yes it's not very clear. We effectively have 2 caches IIUC. @lahabana 

The first layer caches the context based on the Mesh name with a TTL of 1 second.
The first layer caches the context based on the Mesh (name, hash) with a TTL of forever.

If the first layer has a value, use it.
If the first layer is empty, the context is recomputed, cached and also stored in `latestMeshContext`. 

Once the TTL expires, the hash is compared with the current hash and if it's the same, use the value from `latestMeshContext`, otherwise recompute.

So the first layer allows us to ignore Mesh changes for a second, the second allows us to avoid recomputing the context if the hash hasn't changed

**Comment by lahabana** [comment]
Ok so could we just replace the 1second mesh by just storing in the latestMeshContext the lastRecompute time? 

Something like:

```go
type Cache struct {
	meshContextBuilder xds_context.MeshContextBuilder
        expirationTime time.Duration
        rwLock sync.Mutex
        now func() time.Time

	latestMeshContext map[string]*xds_context.MeshContext
}

type entry struct {
   computeTime time.Time
   ctx *xds_context.MeshContext
}

func (c *Cache) GetMeshContext(ctx context.Context, syncLog logr.Logger, mesh string) (xds_context.MeshContext, error) {
   c.rwLock.RLock()
   e, ok := c.latestMeshContext[mesh]
   c.rwLock.RUnlock()
   hash := ""
   if ok {
      hash := e.ctx.hash
      if c.now().Before(e.computeTime.Add(c.expirationTime)) {
          return e.ctx, nil
      }
   }

   meshCtx, err := c.meshContextBuilder.BuildIfChanged(ctx, mesh, hash)
   if err != nil {
     return nil, err
   }
   c.rwLock.Lock()
   c.latestMeshContext[mesh] = entry{ctx: meshCtx, computeTime: c.now()}
   c.rwLock.Unlock()
   return meshCtx, nil
}
```

This doesn't do the once to avoid concurrent calls to `meshContextBuilder` but I think you could adapt this easily with a once too. I think this avoids this complex layering of caches.

**Pull request closed without merging**
