### PR TITLE
chore(*) upgrade Envoy to v1.19.1

### PR DESCRIPTION
**Pull request by jpeach**
Signed-off-by: James Peach <james.peach@konghq.com>

### Summary

Upgrade to Envoy v1.19.1 ([release notes](https://www.envoyproxy.io/docs/envoy/v1.19.1/version_history/current)).

### Full changelog

* Upgrade Envoy to v1.19.1

### Issues resolved

N/A

### Documentation

N/A

### Testing

- [x] Unit tests
- [x] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes 

### Backwards compatibility

- [x] Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.

### CODE REVIEW

**Comment by jakubdyszkiewicz** [comment]
Note: Before merging, we need to make sure that new Envoy binaries are up in https://download.konghq.com/mesh-alpine/

**Comment by jpeach** [comment]
Envoy broke DNS filter compatibility between 1.18 and 1.19. Not sure how we are going to be able to upgrade past this. IIUC, we can't require a big-bang conversion to Envoy 1.19.


https://github.com/envoyproxy/envoy/pull/16237

**Comment by jpeach** [comment]
> Note: Before merging, we need to make sure that new Envoy binaries are up in https://download.konghq.com/mesh-alpine/

How do we do that?

**Comment by jpeach** [comment]
Abandoning the 1.19.1 upgrade. Hopefully we will be able to upgrade to 1.19.2 if the upstream protobuf changes work out.

**Comment by jpeach** [comment]
xref https://github.com/kumahq/kuma/issues/2713

**Pull request closed without merging**
