### PR TITLE
refactor(xds): define GetServiceName for dataplane networking outbound

### PR DESCRIPTION
**Pull request by mmorel-35**
### Checklist prior to review

- [ ] [Link to relevant issue][1] as well as docs and UI issues --
- [ ] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Tests (Unit test, E2E tests, manual test on universal and k8s) --
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [ ] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

> Changelog: skip

### CODE REVIEW

**Comment by mmorel-35** [comment]
Hi @michaelbeaumont ,

In every place `GetTagsIncludingLegacy()`is used to retrieve the ServiceName but in case there are other tags defined they won't find the name of the service.

**Comment by michaelbeaumont** [comment]
@mmorel-35 I think the fix should be a completely separate PR

**Comment by mmorel-35** [comment]
> @mmorel-35 I think the fix should be a completely separate PR

Alright @michaelbeaumont , it's done with https://github.com/kumahq/kuma/pull/7201

**Review by michaelbeaumont — APPROVED** [review]

**Comment by michaelbeaumont** [comment]
Nice one, thanks @mmorel-35 !

**Pull request merged**
