### PR TITLE
feat(helm): use object instead of list for plugins.policies

### PR DESCRIPTION
**Pull request by michaelbeaumont**
This allows it to be 'appended' to by other charts. This is technically a breaking change but we can include this in `UPGRADE.md`.

### Checklist prior to review

- [x] Link to docs PR or issue --
- [x] Link to UI issue or PR --
- [x] Is the [issue worked on linked][1]? --
- [x] The PR does not hardcode values that might break projects that depend on kuma (e.g. "kumahq" as a image registry) --
- [x] The PR will work for both Linux and Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Unit Tests --
- [x] E2E Tests --
- [x] Manual Universal Tests --
- [x] Manual Kubernetes Tests --
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [x] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by slonka** [comment]
> This is technically a breaking change but we can include this in UPGRADE.md.

Please add it there. If we know of any charts (other then ours) that depend on our charts let's also reach out to the maintainers.

**Comment by slonka** [comment]
I think the CI check failed because of https://github.com/kumahq/kuma/pull/5680, merged master.

**Comment by lahabana** [comment]
> This is technically a breaking change but we can include this in UPGRADE.md.

Was this ever released already? I don't think so so it's fine to do a breaking change

**Comment by michaelbeaumont** [comment]
> Was this ever released already? I don't think so so it's fine to do a breaking change

Unfortunately it's in `release-2.0` already.

**Review by jakubdyszkiewicz — APPROVED** [review]

**Review by Automaat — APPROVED** [review]

**Pull request merged**
