### PR TITLE
fix(MeshService): add kuma.io/display-name label to generated MeshService on universal

### PR DESCRIPTION
**Pull request by michaelbeaumont**
These aren't added otherwise. `ComputeLabels` isn't called when using the store directly.

### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues --
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

> Changelog: skip

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Review by slonka — COMMENTED** [review]
Can you add a short description why wy need to do that?

**Comment by michaelbeaumont** [comment]
> Can you add a short description why wy need to do that?

Because it doesn't happen otherwise

**Comment by lobkovilya** [comment]
It's similar to https://github.com/kumahq/kuma/pull/11334 but now about `kuma.io/display-name` label right? Do we need it for MES and MMZS?

**Review by lukidzi — APPROVED** [review]

**Comment by michaelbeaumont** [comment]
> Do we need it for MES and MMZS?

I don't know, how are they being created? the problem here was that we're creating them directly with the store and the labels aren't added in that case

**Comment by lobkovilya** [comment]
> It's similar to https://github.com/kumahq/kuma/pull/11334 but now about kuma.io/display-name label right? Do we need it for MES and MMZS?

nvm it's just for autogenerated

**Pull request merged**
