### PR TITLE
feat(kuma-cp) virtual host modifications

### PR DESCRIPTION
**Pull request by jakubdyszkiewicz**
### Summary

Virtual Host modification

I think VirtualHost is enough for RDS modifications.

We can skip [RouteConfiguration](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route.proto#envoy-api-msg-routeconfiguration) because VirtualHost offers all headers to add.
Most of the operations on Routes are possible from VirtualHost (you can remove VirtualHost and add another one with a different list of routes, most settings on routes like retries are available on VirtualHost)

### Documentation

https://github.com/kumahq/kuma-website/pull/238

### CODE REVIEW

**Comment by lobkovilya** [comment]
Probably even makes sense to skip VirtualHost as well and give an ability to modify only Routes of `CommonVirtualHost` created by Kuma. Because if you add new VirtualHost then traffic won't go through `CommonVirtualHost` and functionality will be broken.

**Comment by jakubdyszkiewicz** [comment]
```
Probably even makes sense to skip VirtualHost as well and give an ability to modify only Routes of CommonVirtualHost created by Kuma. Because if you add new VirtualHost then traffic won't go through CommonVirtualHost and functionality will be broken.
```
But you can remove default virtual hosts and add new ones.

**Comment by lobkovilya** [comment]
Yes, but in this case, you have to manually write all stuff that Kuma does automatically here:
```go
func (c RouteConfigurer) routeAction() *envoy_route.RouteAction {
	routeAction := envoy_route.RouteAction{}
	if len(c.subsets) == 1 {
		routeAction.ClusterSpecifier = &envoy_route.RouteAction_Cluster{
			Cluster: c.subsets[0].ClusterName,
		}
		routeAction.MetadataMatch = envoy_common.LbMetadata(c.subsets[0].Tags)
	} else {
		var weightedClusters []*envoy_route.WeightedCluster_ClusterWeight
		var totalWeight uint32
		for _, subset := range c.subsets {
			weightedClusters = append(weightedClusters, &envoy_route.WeightedCluster_ClusterWeight{
				Name:          subset.ClusterName,
				Weight:        &wrappers.UInt32Value{Value: subset.Weight},
				MetadataMatch: envoy_common.LbMetadata(subset.Tags),
			})
			totalWeight += subset.Weight
		}
		routeAction.ClusterSpecifier = &envoy_route.RouteAction_WeightedClusters{
			WeightedClusters: &envoy_route.WeightedCluster{
				Clusters:    weightedClusters,
				TotalWeight: &wrappers.UInt32Value{Value: totalWeight},
			},
		}
	}
	return &routeAction
}
```
Is it correct?

**Comment by jakubdyszkiewicz** [comment]
Sure, but if you are going with rewriting VirtualHosts you probably want that.

And if you want to patch routes fields - like I said in the description, most of the settings are available on VirtualHost object

**Pull request merged**
