### PR TITLE
Move type,name,mesh to endpoints.yaml 

### PR DESCRIPTION
**Pull request by ADITYADAS1999**
Move type,name,mesh to endpoints.yaml #5213

Description
Currently we have:

```

 properties: 
   type: 
     description: '' 
     type: string 
   mesh: 
     description: 'Mesh is the name of the Kuma mesh this resource belongs to. 
       It may be omitted for cluster-scoped resources.' 
     type: string 
   name: 
     description: 'Name of the Kuma resource' 
     type: string 


```

this should move in:

https://github.com/kumahq/kuma/blob/master/tools/policy-gen/templates/endpoints.yaml

This would avoid building buggy schema like: https://github.com/kumahq/kuma/blob/master/pkg/plugins/policies/meshaccesslog/api/v1alpha1/schema.yaml

### CODE REVIEW

**Comment by lobkovilya** [comment]
Hi Aditya 👋 Please make sure to run `make check` on your local machine

**Comment by ADITYADAS1999** [comment]
> Hi Aditya 👋 Please make sure to run `make check` on your local machine

How to run  `make check` ,  Please help.

**Comment by lobkovilya** [comment]
It should be relatively simple, you can find instructions [here](https://github.com/kumahq/kuma/blob/master/DEVELOPER.md#code-checks). Also, make sure you have all [dependencies](https://github.com/kumahq/kuma/blob/master/DEVELOPER.md#dependencies) installed.

**Comment by ADITYADAS1999** [comment]
> It should be relatively simple, you can find instructions [here](https://github.com/kumahq/kuma/blob/master/DEVELOPER.md#code-checks). Also, make sure you have all [dependencies](https://github.com/kumahq/kuma/blob/master/DEVELOPER.md#dependencies) installed.

thanks you

**Comment by ADITYADAS1999** [comment]
> It should be relatively simple, you can find instructions [here](https://github.com/kumahq/kuma/blob/master/DEVELOPER.md#code-checks). Also, make sure you have all [dependencies](https://github.com/kumahq/kuma/blob/master/DEVELOPER.md#dependencies) installed.

hi [lobkovilya](https://github.com/lobkovilya) there many Command line tool are present here, but I use only Git, I thing clang-format Git integration is necessary ?

**Comment by lobkovilya** [comment]
Yeah, we're using quite a few tools for development, but you can install all of them using the `make dev/tools` command. The command will download and put all binaries into `${HOME}/.kuma-dev` directory. After that, you should be good to run `make check`.

**Comment by ADITYADAS1999** [comment]
> Yeah, we're using quite a few tools for development, but you can install all of them using the `make dev/tools` command. The command will download and put all binaries into `${HOME}/.kuma-dev` directory. After that, you should be good to run `make check`.

awesome

**Comment by lahabana** [comment]
Superseeded by #5349

**Pull request closed without merging**
