### PR TITLE
docs(resources): rename Dataplane proto fields from camel case to snake case

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Checklist prior to review

It looks like we expect proto fields to have snake case names. This
doesn't change how we deserialize resources because we format the proto
JSON key into camel case. See `transparent_proxying` in the same proto.

We should probably lint the protos (maybe with [`buf`](https://github.com/bufbuild/buf))

- [ ] Link to docs PR or issue --
- [ ] Link to UI issue or PR --
- [ ] Is the [issue worked on linked][1]? --
- [ ] Unit Tests --
- [ ] E2E Tests --
- [ ] Manual Universal Tests --
- [ ] Manual Kubernetes Tests --
- [ ] Do you need to update [`UPGRADE.md`](/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](/CONTRIBUTING.md#backporting)? --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by lahabana** [comment]
I don't understand this point:

> This doesn't change how we deserialize resources because we format the proto JSON key into camel case

I see the generated code actually changed the tags so there must be something I'm missing :)

**Comment by michaelbeaumont** [comment]
Protobuf uses the `json` tag to deserialize if it's set, which is newly set to `advertisedAddress`. See `.transparentProxying`, which was already camel cased.

**Comment by lahabana** [comment]
Ok get it! There's both `protobuf.json` and `json` which is a little confusing indeed :)

**Comment by michaelbeaumont** [comment]
Closing for https://github.com/kumahq/kuma/pull/4764 until we lint our protos.

**Pull request closed without merging**
