### PR TITLE
fix(chart): remove replica from cp-deployment.yaml when autoscaling enabled

### PR DESCRIPTION
**Pull request by gustoliv**
### Summary

This PR fixes cp-deployment.yaml replica count when `controlPlane.autoscaling.enabled == true`.

### Full changelog

* Added conditional replica count in `cp-deployment.yaml` when `controlPlane.autoscaling.enabled`
* Added conditional replica count in `egress-deployment.yaml` when `egress.autoscaling.enabled`
* Added conditional replica count in `ingress-deployment.yaml` when `ingress.autoscaling.enabled`

### CODE REVIEW

**Comment by jakubdyszkiewicz** [comment]
Nice, good catch :)

Could you also fix this for ingress and egress (it follows the same pattern with `ingress.autoscaling.enabled` and `egress.autoscaling.enabled`?


If anyone looking at the PR was wondering
```
Migrating Deployments and StatefulSets to horizontal autoscaling
When an HPA is enabled, it is recommended that the value of spec.replicas of the Deployment and / or StatefulSet be removed from their [manifest(s)](https://kubernetes.io/docs/reference/glossary/?all=true#term-manifest). If this isn't done, any time a change to that object is applied, for example via kubectl apply -f deployment.yaml, this will instruct Kubernetes to scale the current number of Pods to the value of the spec.replicas key. This may not be desired and could be troublesome when an HPA is active.

Keep in mind that the removal of spec.replicas may incur a one-time degradation of Pod counts as the default value of this key is 1 (reference [Deployment Replicas](https://kubernetes.io/docs/concepts/workloads/controllers/deployment#replicas)). Upon the update, all Pods except 1 will begin their termination procedures. Any deployment application afterwards will behave as normal and respect a rolling update configuration as desired. You can avoid this degradation by choosing one of the following two methods based on how you are modifying your deployments:
```
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by lahabana** [comment]
Should this be backported to 1.7 too?

**Comment by gustoliv** [comment]
@jakubdyszkiewicz now also fixed in egress and ingress deployments ;)

**Review by bartsmykla — APPROVED** [review]
lgtm

**Pull request merged**
