### PR TITLE
test(policy): add extra testing of the matching algorithm

### LINKED ISSUE #8484: Rule merging alghoritm is not sorting lexographically on MeshTrafficPermission
### What happened?

My intention is to create a `MeshTrafficPermission` set of rules that will allow connectivity from some services and ShadowDeny (or Deny) everything else. 

To achieve that i did a 2 `MeshTrafficPermission` objects, both on  `MeshSubset` targetRef level.

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  labels:
    kuma.io/mesh: default
  name: default-demo-app
  namespace: kuma-system
spec:
  targetRef:
    kind: MeshSubset
    tags:
      k8s.kuma.io/service-name: demo-app
  from:
    - default:
        action: Allow
      targetRef:
        kind: MeshSubset
        tags:
          app.kubernetes.io/name: ui
    - default:
        action: Allow
      targetRef:
        kind: MeshSubset
        tags:
          app.kubernetes.io/name: service-order
    - default:
        action: Allow
      targetRef:
        kind: MeshSubset
        tags:
          app.kubernetes.io/name: service-payment
---

apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  labels:
    kuma.io/mesh: default
  name: default-demo-app-b
  namespace: kuma-system
spec:
  targetRef:
    kind: MeshSubset
    tags:
      k8s.kuma.io/service-name: demo-app
  from:
    - default:
        action: Deny
      targetRef:
        kind: Mesh
```

This setup works fine if naming is like `myrule` for allow set and `myrule-a` for denyset. I see in UI that rules are applied in correct order:
Screenshot 2023-11-28 at 15 54 03

My tests also shows that traffic works as expected

However, when I try to use names like `rule-a` and `rule-b` order is opposite to expected and tests also failing.

Screenshot 2023-11-28 at 15 56 25

I am not sure how sorting is working, but looks like that not according to doc which state that `2. At the same level we use lexicographic order on name`.

### PR DESCRIPTION
**Pull request by lahabana**
- Add some tests to the policy matching algo
- Add possibility to add a test as pending in `test.EntriesForFolder`

Ref #8484

### Checklist prior to review

- [ ] [Link to relevant issue][1] as well as docs and UI issues --
- [ ] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by lobkovilya** [comment]
Tests in this PR are not expected to pass, because sorting normally is happening here https://github.com/kumahq/kuma/blob/b249dab0157cf18dee9968ef24a51a4901bc9c6b/pkg/plugins/policies/core/matchers/dataplane.go#L63-L67

But the test calls `core_rules.BuildFromRules` function that already expects sorted policies as input.

**Comment by lobkovilya** [comment]
If you place the same test here `pkg/plugins/policies/core/matchers/dataplane_test.go`, it works as expected.

**Comment by lahabana** [comment]
Yeah that's what I've noticed later

**Comment by lahabana** [comment]
Yeah I noticed that after so I added tests there as well and it seems to be working correctly. So need to understand the issue some more

**Pull request merged**
