### PR TITLE
feat(kuma-cp): support labels in ResourceMeta

### PR DESCRIPTION
**Pull request by lobkovilya**
### Checklist prior to review

- [X] [Link to relevant issue][1] as well as docs and UI issues --
- [X] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [X] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [X] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [X] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by lobkovilya** [comment]
@jakubdyszkiewicz added tests as you suggested. The validation for Universal was missing, so I added it as well

**Comment by jakubdyszkiewicz** [comment]
The unit test is flaky. Please add a description (link the issue at least)

**Review by jakubdyszkiewicz — APPROVED** [review]

**Review by jakubdyszkiewicz — APPROVED** [review]
approved but do not merged. I'm testing upgrades

**Review by jakubdyszkiewicz — CHANGES_REQUESTED** [review]
Simple upgrade is broken

```
2023-12-14T15:57:36.940+0100	ERROR	kuma-cp.run	problem running Control Plane	{"error": "failed to execute query: SELECT spec, version, creation_time, modification_time, labels FROM resources WHERE name=$1 AND mesh=$2 AND type=$3;: can't scan into dest[4]: cannot scan NULL into *string", "errorVerbose": "can't scan into dest[4]: cannot scan NULL into *string\nfailed to execute query: SELECT spec, version, creation_time, modification_time, labels FROM resources WHERE name=$1 AND mesh=$2 AND type=$3;\ngithub.com/kumahq/kuma/pkg/plugins/resources/postgres.(*pgxResourceStore).Get\n\tgithub.com/kumahq/kuma/pkg/plugins/resources/postgres/pgx_store.go:247\ngithub.com/kumahq/kuma/pkg/core/resources/store.(*paginationStore).Get\n\tgithub.com/kumahq/kuma/pkg/core/resources/store/pagination_store.go:42\ngithub.com/kumahq/kuma/pkg/metrics/store.(*MeteredStore).Get\n\tgithub.com/kumahq/kuma/pkg/metrics/store/store.go:72\ngithub.com/kumahq/kuma/pkg/core/config/manager.(*configManager).Get\n\tgithub.com/kumahq/kuma/pkg/core/config/manager/manager.go:36\ngithub.com/kumahq/kuma/pkg/clusterid.(*clusterIDCreator).create\n\tgithub.com/kumahq/kuma/pkg/clusterid/creator.go:33\ngithub.com/kumahq/kuma/pkg/clusterid.(*clusterIDCreator).Start\n\tgithub.com/kumahq/kuma/pkg/clusterid/creator.go:22\ngithub.com/kumahq/kuma/pkg/core/runtime/component.(*manager).startLeaderComponents.func2.1\n\tgithub.com/kumahq/kuma/pkg/core/runtime/component/component.go:180\nruntime.goexit\n\truntime/asm_arm64.s:1197"}
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/kumahq/kuma/app/kuma-cp/cmd.Execute
	github.com/kumahq/kuma/app/kuma-cp/cmd/root.go:83
main.main
	github.com/kumahq/kuma/app/kuma-cp/main.go:6
runtime.main
	runtime/proc.go:267
Error: failed to execute query: SELECT spec, version, creation_time, modification_time, labels FROM resources WHERE name=$1 AND mesh=$2 AND type=$3;: can't scan into dest[4]: cannot scan NULL into *string
```

checkout to master. Run `make CP_STORE=postgres run/kuma-cp`. Checkout to this branch, run the same and it fails

**Review by jakubdyszkiewicz — APPROVED** [review]

**Pull request merged**
