### PR TITLE
fix(MeshHttpRoute): don't split header value prematurely

### LINKED ISSUE #10156: When modifying the headers, split the value may cause unexpected bug
### What happened?

In https://github.com/kumahq/kuma/blob/5c1f62de50047e0c082ec6d8f92337a12c27ce47/pkg/plugins/policies/meshhttproute/xds/filters/requestheadermodifier.go#L36

the header value is split by `,`, and then added one by one.

In case like `Set-Cookie: id=a3fWa; Expires=Wed, 21 Oct 2015 07:28:00 GMT`, it will be added as:
`Set-Cookie: id=a3fWa; Expires=Wed` and
`Set-Cookie: 21 Oct 2015 07:28:00 GMT`

I wonder why not set the header directly without any splitting?

### PR DESCRIPTION
**Pull request by spacewander**
Fix #10156
Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### Checklist prior to review

- [x] [#10156][1] as well as docs and UI issues --
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by spacewander** [comment]
Will fix the unit test later.

**Comment by slonka** [comment]
from the issue:

> I think Envoy will do the right thing here, we should change this.

@michaelbeaumont did you by any chance had time to check if it does the right thing?

**Review by slonka — COMMENTED** [review]
from the issue:

> I think Envoy will do the right thing here, we should change this.

@michaelbeaumont did you by any chance had time to check if it does the right thing?

**Review by michaelbeaumont — APPROVED** [review]
LGTM, thanks @spacewander !

**Pull request merged**
