### PR TITLE
feat(kuma-cp) workdir for autogenerated certs

### PR DESCRIPTION
**Pull request by lobkovilya**
### Summary

Today, if the user doesn't explicitly, provide TLS cert and key Kuma will autogenerate TLS cert and key in the temporary directory with a random name. That's not great since even using PostgreSQL kuma-dp can't reconnect to kuma-cp in case of restart. 

Current PR fixes this problem by introducing a working directory. It works well, but I'm not sure what should be a default value for `workDir`? It'd be nice to have `/var/run/kuma` or something like this, but it introduces a bit of a bad UX on MacOS for example, where by default `kuma-cp` doesn't have enough permissions. Right now default value is `./kuma`

### Issues resolved

Fix https://github.com/kumahq/kuma/issues/413

### Documentation

- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)

### CODE REVIEW

**Comment by subnetmarco** [comment]
In Kong the default working directory is `/usr/local/kong`, so for us it could be `/usr/local/kuma`. 

We also need to allow the user to change the default working directory via the configuraiton.

If the working directory does not exist, we must create it. If it cannot be created, `kuma-cp` must show an error.

**Review by subnetmarco — CHANGES_REQUESTED** [review]
As per my comment.

**Comment by lobkovilya** [comment]
@subnetmarco I changed the default working directory to `/usr/local/kuma`, now if you just run `kuma-cp run` on MacOS you'll see the following error:
```
Error: could not autogenerate TLS certificate: failed to save auto-generated TLS cert and key into a working directory: failed to create a file with TLS cert: open /usr/local/kuma/kuma-cp.crt: permission denied, working directory could be changed using KUMA_GENERAL_WORK_DIR environment variable
```

**Comment by lobkovilya** [comment]
@subnetmarco I updated PR, now on MacOS it's defaulting to `~/Library/Kuma`, on linux-based - `/opt/kuma`. I was in the process of writing the documentation and I think it's still can be confusing. If you run Linux, not as a Docker container, but as a VM - you'll have some non-default user by default, which doesn't have permissions to write to either directory under `/` (nor `/usr/` nor `/opt`).

I think the best we can do - always be defaulting to `~/.kuma` regardless of the OS.

**Review by subnetmarco — APPROVED** [review]

**Review by nickolaev — APPROVED** [review]

**Review by bartsmykla — APPROVED** [review]
lgtm

**Pull request merged**
