### PR TITLE
feat(helm): add resource management for jobs

### PR DESCRIPTION
**Pull request by gdasson**
### Summary

Currently, crd/webhook/ns jobs don't have
resource management (requests and limits)
context. Adding resource management to
these jobs.

* add resource management for jobs

### Full changelog

* Implement resource management for crd/webhook/ns jobs 

### Testing

- [ ] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [X] Manual testing on Kubernetes

### Backwards compatibility

Doesn't impact backward compatibility

### CODE REVIEW

**Comment by gdasson** [comment]
@johnharris85 @jakubdyszkiewicz @lahabana : Two questions:

1) I have added the context directly in the jobs' manifest. Is that fine or should I specify them in values.yaml to be rendered by helm? Since these are one-off jobs I thought hardcoding in manifest is fine.
2) If the answer to question 1 above is yes, could you please review and validate that the values that I have set look fine? I can adjust them based on review comments.

Thanks!

**Comment by lahabana** [comment]
Agreed on 1 not really any point in having that be customizable. Does it make sense to have requests and limits be equal?

**Comment by jakubdyszkiewicz** [comment]
I'm ok with hardcoding it. If we ever hit a limit in hooks, our E2E should catch that.

**Comment by gdasson** [comment]
@lahabana : I thought the limits as like an upper bound that may ideally never reach for these particular items. I don’t mind setting them equal either. What’s the values I should set them to?

**Comment by johnharris85** [comment]
Ye I think equal is safest. All these jobs are doing is running `kubectl` so probably the lower bounds that you have right now should be fine.

**Comment by lahabana** [comment]
> @lahabana : I thought the limits as like an upper bound that may ideally never reach for these particular items. I don’t mind setting them equal either. What’s the values I should set them to?

My thinking on these things is: you'll be above request and under limits when it's under stress. It's likely that when this is under stress it's not the only thing under stress. So by setting different requests/limits you are delaying discovering you are reaching capacity to when the system is under full stress which might not be what you want if you can live with a bit of over-provisioning :)

**Comment by lahabana** [comment]
@gdasson planning on updating this or should we take this forward?

**Comment by lahabana** [comment]
As this is going to conflict with #4220 it would be good to have this merged soon

**Comment by gdasson** [comment]
Closing this PR and opening a fresh one with incorporated review comments: https://github.com/kumahq/kuma/pull/4254

**Pull request closed without merging**
