### PR TITLE
ci(lint): increase lint timeout because actions are failing to complete

### PR DESCRIPTION
**Pull request by slonka**
https://github.com/kumahq/kuma/actions/runs/4605675401/jobs/8138008186#step:9:32

> Changelog: skip

### Checklist prior to review

- [X] [Link to relevant issue][1] as well as docs and UI issues --
- [X] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [X] Tests (Unit test, E2E tests, manual test on universal and k8s) --
- [X] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [X] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [X] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by slonka** [comment]
Side question, why is it using [release-1.5 binaries](https://github.com/kumahq/kuma/actions/runs/4605675401/jobs/8138008186#step:9:10)? 

```
GOMEMLIMIT=7GiB CGO_ENABLED=0  /home/runner/.kuma-dev/kuma-release-1.5/bin/golangci-lint run --timeout=10m -v 
```

maybe @lahabana or @lukidzi knows because I think you were the ones who introduced tools versioning.

**Comment by lahabana** [comment]
Weird indeed that's extracted in `version.sh`

**Comment by lahabana** [comment]
Weird:

image


GH says only 5mins passed...

**Comment by lukidzi** [comment]
Not sure why it has version `release-1.5` maybe there is some tag ordering difference? Looks like it takes dir `release-1.5` but the binaries seems to be newer

**Comment by lahabana** [comment]
@slonka what should we do with this?

**Comment by slonka** [comment]
> @slonka what should we do with this?

let's close this for now, it's not happening again, maybe there was some weird clock skew at GH

**Pull request closed without merging**
