### PR TITLE
fix(kuma-dp): fix conntrack collisions 

### PR DESCRIPTION
**Pull request by johnharris85**
### Summary

When there are a lot of DNS queries and a smaller set of ephemeral ports, conntrack collisions could cause DNS traffic to bypass the mesh. The original fix is in Istio's transparentproxy but came in after we vendored that code. 

Original fix here: (https://github.com/istio/istio/pull/33572).

I also pulled across the Istio package's test changes but it looks like we skip tests for this vendored package anyway? Should we bring these back in?

Should probably also backport this.

### Full changelog

Implement conntrack zones in the iptables rules based on a fix in Istio

### Issues resolved

N / A

### Documentation

N / A

### Testing

- [ ] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes

### Backwards compatibility

- [ ] Update [`UPGRADE.md`](UPGRADE.md) with any steps users will need to take
      when upgrading.
- [X] Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.

Signed-off-by: John Harris <john.harris@konghq.com>

### CODE REVIEW

**Comment by lahabana** [comment]
@mergifyio update

**Comment by lahabana** [comment]
@johnharris85 thanks! Do you want to look at reenabling the tests?

**Comment by bartsmykla** [comment]
@johnharris85 Hi John, as we discussed yesterday I want to help with finishing this PR. Would you be able to allow me to contribute to your fork please?

**Comment by bartsmykla** [comment]
As our e2e tests for universal are done from inside of a docker
container, to make the networking work, we are bridging docker
network to the host, which results in additional iptables rules
inside every container within this network. Problem with these
rules is that it's doing some NAT'ing for DNS udp datagrams with
addition of randomly picked (during the container startup) port.
It's problematic for this conntrack change as it works inside
the `raw` table and among others `PREROUTING` chain and expects
the datagrams from known port (53), which the earlier described
NAT'ing is changing. This probably could be fixed by rethinking
some of the rules, but as it's an edge case, after consultation
with the team I decided it's not worth the time needed to properly
solve it and instead I introduced to a `--skip-dns-conntrack-zone-split`
flag for `kumactl install transparent-proxy`, which allows us to
skip attaching the conntrack-collision iptables rules. This change
was necessary for making some of the tests to work (univeral).

I also fixed the code to include our flag for capturing all dns
traffic and instead of hardcoding port `15053`, to use the one
from the configuration.

**Review by lahabana — APPROVED** [review]

**Pull request merged**
