### PR TITLE
ci(stability): make non tls should route to external service repeatable [WIP]

### PR DESCRIPTION
**Pull request by slonka**
trying to reproduce `[It] External Services non-TLS should route to external-service` flake.

### Checklist prior to review

- [ ] [Link to relevant issue][1] as well as docs and UI issues --
- [ ] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Tests (Unit test, E2E tests, manual test on universal and k8s) --
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [ ] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by bartsmykla** [comment]
@slonka what is the status of this work?

**Comment by bartsmykla** [comment]
@slonka ping

**Comment by slonka** [comment]
Hey, sorry. I was trying to reproduce mentioned issue but my on duty ended and I did not have time since. I see CI is not failing as often on this so maybe we can close this and reopen if needed.

**Comment by bartsmykla** [comment]
> Hey, sorry. I was trying to reproduce mentioned issue but my on duty ended and I did not have time since. I see CI is not failing as often on this so maybe we can close this and reopen if needed.

Let's do it

**Pull request closed without merging**
