### PR TITLE
fix(ci) Fix gateway test to work with ipv6

### PR DESCRIPTION
**Pull request by lahabana**
missing quotes in yaml template was causing bad syntax when using ipv6
This is because we were getting addresses like "[::]:8080" which without
quotes would look like an array syntax in yaml

### CODE REVIEW

**Comment by lahabana** [comment]
@jpeach the ipv6 test is still failing but I think now it's a real gateway issue rather than problems in the test.

**Comment by jpeach** [comment]
@lahabana This is probably https://github.com/envoyproxy/envoy/issues/10489

**Comment by lahabana** [comment]
If that's the case regular externalServices have this issue too as it looks like the cluster addition is the same in both cases.
If that's the case I'll update this PR to skip this test and will work on correctly fixing this issue.

**Comment by lahabana** [comment]
Ok confirmed this is the issue. Going to mark this test as ignored when on ipv6 and will fix as part of #3096 .

**Review by jakubdyszkiewicz — APPROVED** [review]

**Pull request merged**
