### PR TITLE
test(e2e): enable reachable services test and increase interval

### PR DESCRIPTION
**Pull request by lukidzi**
### Checklist prior to review

It seems a time of default 5s https://github.com/kumahq/kuma/blob/master/pkg/test/ginkgo.go#L39 in consistently wasn't enough in this case

- [ ] [Link to relevant issue][1] as well as docs and UI issues -- fix: https://github.com/kumahq/kuma/issues/9349
- [ ] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by jakubdyszkiewicz** [comment]
> The default time is 100ms with a 10ms interval

Is it though? https://github.com/kumahq/kuma/blob/master/pkg/test/ginkgo.go#L39

**Comment by lukidzi** [comment]
> 

> > The default time is 100ms with a 10ms interval
> 
> Is it though? https://github.com/kumahq/kuma/blob/master/pkg/test/ginkgo.go#L39

Didn't notice this configuration 😕

**Comment by slonka** [comment]
@jakubdyszkiewicz and @lukidzi what's the way forward here? should we run it a couple of times to see it's not flaky any more and merge it?

**Comment by michaelbeaumont** [comment]
@lukidzi should we close this until it can make progress?

**Comment by jakubdyszkiewicz** [comment]
We now have much more stable CI. Let's merge it if it passes. If it fails we will revert once again

**Review by jakubdyszkiewicz — APPROVED** [review]

**Pull request merged**
