### PR TITLE
chore(deps): upgrade envoy version to 1.26.2

### PR DESCRIPTION
**Pull request by lukidzi**
- [X] [Link to relevant issue][1] as well as docs and UI issues --
- [X] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [X] Tests (Unit test, E2E tests, manual test on universal and k8s) --
- [X] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [X] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [X] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

> Changelog: chore(deps): bump Envoy from v1.25.4 to v1.26.2

### CODE REVIEW

**Comment by lahabana** [comment]
I think we need to backport right? I see a bunch of CVEs in there

**Comment by lukidzi** [comment]
The question is: 
branch < release-2.2 are using 1.22.10 which has no more releases
branch = release-2.2 is using 1.25.4 ( we can upgrade 1.25.7 or change to 1.26(but what about new features) https://github.com/envoyproxy/envoy/releases/tag/v1.25.7)

**Review by slonka — APPROVED** [review]
if the tests pass then 👍 . Also are we 100% sure this is the only place we need to change?

**Comment by lukidzi** [comment]
> if the tests pass then 👍 . Also are we 100% sure this is the only place we need to change?
I think this is the only place

**Pull request merged**
