### PR TITLE
fix(MeshTrace): invalid sampling default values

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues --
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Review by slonka — COMMENTED** [review]
Don't we need to add a test to prevent re-introducing this? How did this pass `validation` tests the first time?

ok so the original PR never changed the tests to check if it work 👀 https://github.com/kumahq/kuma/blob/5d0f0648c22ea1b9e49da469fd31b9b8386a0455/pkg/plugins/policies/meshtrace/api/v1alpha1/validator_test.go#L49

**Comment by michaelbeaumont** [comment]
> Don't we need to add a test to prevent re-introducing this? How did this pass validation tests the first time?

So would we have validation that sets every object field to the empty value to test if the default values of that field's fields are correct?

**Comment by michaelbeaumont** [comment]
> ok so the original PR never changed the tests to check if it work 👀 

In particular this only shows up if `sampling:` is set but not all the fields are set.

**Comment by slonka** [comment]
> So would we have validation that sets every object field to the empty value to test if the default values of that field's fields are correct?

That will also be beneficial. It's just that if we change the default from "100" to "100%" then we **NEED** to change the unit tests as well.

**Comment by michaelbeaumont** [comment]
> It's just that if we change the default from "100" to "100%" then we NEED to change the unit tests as well.

What exactly would the test test, just that the default values we enter aren't invalid?

Note this also only shows up with Kubernetes because of #6070

**Comment by slonka** [comment]
@michaelbeaumont can you add an error case with explicit "80%"?

**Comment by michaelbeaumont** [comment]
> @michaelbeaumont can you add an error case with explicit "80%"?

What would that test?

**Comment by slonka** [comment]
> What would that test?

well exactly the problem that we hit 🤔

**Review by slonka — APPROVED** [review]

**Pull request merged**
