### PR TITLE
feat(helm): allow specifying security context

### PR DESCRIPTION
**Pull request by gdasson**
### Summary

Currently, there is no place to specify/customize
the securityContext for following components:
kuma-cp/ Jobs (crd/webhook/ns)/ Ingress / Egress / CNI
This PR provides the option to specify securityContext
for all of the above components and sets the default
values for each one of them.

### Full changelog

* Implemented securityContext for : 
      kuma-cp/ Jobs (crd/webhook/ns)/ Ingress / Egress / CNI
* Updated tests for new changes
* Fix https://github.com/kumahq/kuma/issues/3989

### Issues resolved

Fix #https://github.com/kumahq/kuma/issues/3989

### Testing

- [ ] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [X] Manual testing on Kubernetes

### Backwards compatibility
Does not affect backward compatibility

### CODE REVIEW

**Comment by gdasson** [comment]
@johnharris85, @jakubdyszkiewicz, @lahabana : Could you please review the defaults? Please let me know for corrections on default values. Thanks!

**Comment by lahabana** [comment]
Sounds good! The tests failed in a way that indicates the context is not right. From a quick look it seems weird to drop all capabilities on the cni container for example but we'd need to check some more.

**Comment by lahabana** [comment]
Hey @gdasson I don't know if you've seen what @bartsmykla said on Kuma slack: https://kuma-mesh.slack.com/archives/C013ALVE1GU/p1649423921216259

> Hi [@Gaurav Dasson](https://kuma-mesh.slack.com/team/U03ACAWEU6R). I'm working on reviewing https://github.com/kumahq/kuma/pull/4111 as I want to help and make sure it will be included in our next release. The only problem I have with this PR are the default values. I think we should remove changes in securityContexts in values.yaml (maybe by commenting them out?). I like the idea of least privilege approach but it's hard to predict without longer testing how kuma will behave with the new defaults. If we would decide to do these kind of tests, the PR would definitely slip from the next release. What do you think about commenting out values in the values.yaml files and regenerating golden files?

I think it makes sense WDYT? Can you update your PR soon? We're cutting 1.6.0 Monday and we'd love to have this in

**Comment by gdasson** [comment]
@lahabana @bartsmykla : Thanks for the feedback. Sure, let me remove the default values. It would give the option to the consumer to then set values if they really want. Will update the PR within next one hour. Wait for me.. let this PR make it to the train leaving the station..let me run run run.. :D

**Comment by gdasson** [comment]
Opening a new PR to avoid rebase and force commit issues.

**Pull request closed without merging**
