### PR TITLE
chore: skip Compute when building inbound access logs

### PR DESCRIPTION
**Pull request by jakubdyszkiewicz**
It does not make sense to call Compute when building the rules for `from` section.
For example, MeshTrafficPermission takes 1:1 fromRules and create list form it.

It does not change the current behavior, it's just confusing when reading the code.

### Checklist prior to review

- [X] Link to docs PR or issue -- nope
- [X] Link to UI issue or PR -- nope
- [X] Is the [issue worked on linked][1]? -- no, noticed while working on other stuff
- [X] The PR does not hardcode values that might break projects that depend on kuma (e.g. "kumahq" as a image registry) --
- [X] The PR will work for both Linux and Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [X] Unit Tests --
- [X] E2E Tests --
- [X] Manual Universal Tests --
- [ ] Manual Kubernetes Tests --
- [X] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? -- no
- [X] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? -- no
- [X] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Review by lahabana — APPROVED** [review]

**Comment by michaelbeaumont** [comment]
I actually find calling `Compute` for both to and from easier to understand than why we take only the first `fromRules`. And it won't break if we introduce support for more than `Mesh`

**Comment by jakubdyszkiewicz** [comment]
But I think passing Service of DP for which we are building rules to `Compute` was not correct and it worked by accident (because "superset" is always Mesh so you can pass whatever). If we want to keep Compute, we would need to pass `Mesh` subset, which I think is equivalent of not calling Compute.

The origin of this PR was that I was building rule inspect API and I built it based on the logic of access log, but the `Compute` of Service of DP did not work at all for MeshTrafficPermission

I think introducing support for more than `Mesh` will break this logic anyways.

**Review by michaelbeaumont — APPROVED** [review]
> If we want to keep Compute, we would need to pass Mesh subset, which I think is equivalent of not calling Compute.

Yeah you're right, the `from.targetRef` is not intended to be a refinement of the _inbound_ the traffic came to but rather a refinement on the _service_ the traffic came from (to whatever inbound). 

Which we have no idea of here, so we'd have to call `Compute(Mesh)`. Is that bad though? I like the idea of staying in the restricted "refinement logic" of subsets for as long as possible here. I think in general it also works for `from`, it's just that we don't have any information.

Like if theoretically we allowed `MeshService` for some reason or a `MeshService` somehow did end up in `rules`, the end result would be the correct empty set because `Mesh` is not a subset of `MeshService` (or of anything besides `Mesh`). The logic still applies. Does that make sense?

I'll approve since this it's less wrong than before.

**Comment by jakubdyszkiewicz** [comment]
Ok, I think I don't mind either way, so changed to call `Compute`, but with MeshSubset

**Review by lahabana — APPROVED** [review]

**Review by michaelbeaumont — APPROVED** [review]

**Pull request merged**
