### PR TITLE
chore(kuma-cp): pass context.Context to plugin.Apply

### PR DESCRIPTION
**Pull request by michaelbeaumont**
Get rid of the current [use of `context.TODO()` in MeshHTTPRoute plugin](https://github.com/kumahq/kuma/pull/8782/files#diff-2d4e9cddeb9533b7e939184577a3c8dd84271a49d7b58919a8fc2612c595ab63L79-R79).

### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues --
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by bartsmykla** [comment]
I don't see it being used now. Could you update the PR description with information why it's necessary?

**Comment by michaelbeaumont** [comment]
> I don't see it being used now. Could you update the PR description with information why it's necessary?

https://github.com/kumahq/kuma/pull/8782/files#diff-2d4e9cddeb9533b7e939184577a3c8dd84271a49d7b58919a8fc2612c595ab63L79-R79

**Comment by jakubdyszkiewicz** [comment]
so in the end this is used in the `datasource.Loader` only? We know that the implem used in xds config does not use I/O therefore context is irrelevant.

I'd consider passing `context.TODO()` or nil or whatever in `loadBytes` func instead of bringing the context through all layers. Alternatively, we could make `staticLoader` public, add a `LoadStatically` (or similar) func that does not require context at all.

I'd like to discourage users of using I/O in xds generation. My long-term plan was to ban I/O in XDS generators so instead of goroutines with tickers we could do a queue-based approach, because the process would be purely CPU-bound.

**Comment by michaelbeaumont** [comment]
Yeah it's a good point

**Pull request closed without merging**
