### PR TITLE
chore(kuma-dp): cleanup bootstrap version field

### LINKED ISSUE #2986: Delete 'BootstrapVersion' field from BootstrapRequest
### Summary

After the update to Envoy 1.20 we got rid of the support of the bootstrap version. But the field BootstrapVersion is left in the BootstrapRequest, so new kuma-dp could request an old kuma-cp. 

The current issue aims to track TODOs:
- delete `BootstrapVersion` field from BootstrapRequest
- delete deprecated kuma-dp CLI flag `--bootstrap-version`

### PR DESCRIPTION
**Pull request by tharun208**
### Summary

This PR deletes the `BootstrapVersion` field from BootstrapRequest.

### Full changelog

* Removed the `BootstrapVersion` field
* Updated tests

### Issues resolved

Fix #2986

### Documentation

- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)

### Testing

- [x] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes

### Backwards compatibility

- [ ] Update [`UPGRADE.md`](/UPGRADE.md) with any steps users will need to take when upgrading.
- [ ] Add `backport-to-stable` label if the code follows our [backporting policy](/CONTRIBUTING.md#backporting)

### CODE REVIEW

**Comment by lahabana** [comment]
I think this makes sense @lobkovilya can you double check as the TODO was coming from you :)

**Comment by lobkovilya** [comment]
If I recall correctly, we didn't release Kuma with Envoy 1.20 (even though it's in master for a while). We've left this field for compatibility reasons, so new kuma-dp could request an old kuma-cp. So I think we should postpone merging this PR.

**Comment by lahabana** [comment]
@lobkovilya now that we are running 1.21 can we do this? Or should we wait another PR?

**Comment by jakubdyszkiewicz** [comment]
@tharun208 we are ready to merge it, but could you merge the newest origin/master before it?

**Comment by tharun208** [comment]
@jakubdyszkiewicz done 👍🏻

**Comment by lahabana** [comment]
@mergifyio update

**Comment by lahabana** [comment]
@jakubdyszkiewicz ok to merge?

**Review by jakubdyszkiewicz — APPROVED** [review]

**Pull request merged**
